version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_DEFAULT
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/data/postgres
  api:
    container_name: esculappio
    build: .
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/usr/app
    ports: 
      - 7000:7000