version: "3.7"

services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_DEFAULT
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"